baseURL: "/"  # 修改为根路径
languageCode: "zh-CN"
title: "我的自传体"
# 开启章节 collection
module:
  mounts:
    - source: content/chapters
      target: content/chapters
outputs:
  home: ["HTML", "RSS"]
# 关闭 taxonomy（用不到）
disableKinds: ["taxonomy", "term"]
# 让 Hugo 处理 .yaml 数据
dataDir: data

