[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.146.7"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_URL"

[dev]
  command = "hugo server -D"
  port = 8888
  publish = "public"
  autoLaunch = true
  framework = "#custom"
  targetPort = 1313

[dev.identity]
  port = 9999

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://identity.netlify.com https://unpkg.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://identity.netlify.com"

