backend:
  name: github
  repo: crazyoldmanll/time-recording
  branch: main
  commit_messages:
    create: '创建 {{collection}} "{{slug}}"'
    update: '更新 {{collection}} "{{slug}}"'
    delete: '删除 {{collection}} "{{slug}}"'
    uploadMedia: '上传媒体文件 "{{path}}"'
    deleteMedia: '删除媒体文件 "{{path}}"'

# 本地开发配置 - 只在本地开发时使用
local_backend:
  # 当部署到生产环境时，这个配置不会生效
  url: http://localhost:8081/api/v1
  allowed_hosts: ['localhost']

# 移除硬编码的localhost链接
# 改为相对路径或自动检测当前域名
site_url: /
display_url: /
logo_url: /images/logo.png

publish_mode: editorial_workflow

media_folder: "static/images/chapter-thumbs"
public_folder: "/images/chapter-thumbs"

# Markdown编辑器配置
editor:
  preview: true

# 配置Markdown编辑器
markdown:
  default_mode: 'rich_text'
  frontmatter_delimiter: ['---', '---']
  show_raw: true
  editor_components: ['image', 'code-block', 'quote', 'bulleted-list', 'numbered-list', 'table']
  toolbar_buttons: ['bold', 'italic', 'code', 'link', 'heading-one', 'heading-two', 
                 'heading-three', 'heading-four', 'heading-five', 'heading-six',
                 'quote', 'bulleted-list', 'numbered-list']

# slug配置
slug:
  encoding: "unicode"
  clean_accents: false
  sanitize_replacement: "-"

# 支持中文的配置
locale: 'zh_Hans'

# 清除本地缓存
local_backend_cache: false

collections:
  - name: "books"
    label: "书籍"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", required: true, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { label: "描述", name: "description", widget: "string", required: false, hint: "书籍简短描述" }
      - { label: "封面", name: "cover", widget: "image", required: false, hint: "书籍封面图片" }
      - { 
          label: "正文", 
          name: "body", 
          widget: "text",
          default: "书籍介绍内容...",
          hint: "书籍详细介绍"
        }

  - name: "chapters"
    label: "章节"
    folder: "content/chapters"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", required: true, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { 
          label: "所属书籍", 
          name: "book", 
          widget: "relation",
          collection: "books",
          search_fields: ["title"],
          value_field: "{{slug}}",
          display_fields: ["title"],
          required: true
        }
      - { label: "章节 ID", name: "id", widget: "string", required: false, hint: "可选，用于唯一标识" }
      - { label: "缩略图", name: "thumb", widget: "image", required: false, hint: "可选，章节缩略图" }
      - { 
          label: "正文", 
          name: "body", 
          widget: "text",
          default: "这里可以输入文章内容...",
          hint: "支持图文混排，可以粘贴保留格式的文本"
        }

  - name: "settings"
    label: "设置"
    files:
      - name: "chaptersData"
        label: "章节列表 (顺序)"
        file: "data/chapters.yaml"
        fields:
          - label: "章节"
            name: "chapters"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "标题", name: "title", widget: "string" }
              - { label: "缩略图", name: "thumb", widget: "string" }

