backend:
  name: git-gateway
  local_backend: true
  branch: main
  repo：crazyoldmanll/time-recording
  commit_messages:
    create: '创建 {{collection}} "{{slug}}"'
    update: '更新 {{collection}} "{{slug}}"'
    delete: '删除 {{collection}} "{{slug}}"'
    uploadMedia: '上传媒体文件 "{{path}}"'
    deleteMedia: '删除媒体文件 "{{path}}"'

# 本地开发时使用 - 指定明确的URL
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts: ['localhost']

# 启用编辑预览 - 使用相对路径避免硬编码域名
site_url: http://localhost:1313
display_url: http://localhost:1313
logo_url: http://localhost:1313/images/logo.png

publish_mode: editorial_workflow

# 媒体库配置 - 改进媒体管理
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey" # 请替换为您的uploadcare key
    multiple: true
    tabs: "file url camera gdrive gphotos"
    effects: "crop,rotate,enhance,sharp,blur"
    imageShrink: "2000x2000"
    previewStep: true
    clearable: true

# Markdown编辑器高级配置
editor:
  preview: true
  frame: true # 启用框架模式，更好的编辑体验

# 增强的Markdown编辑器配置
markdown:
  default_mode: 'rich_text'
  frontmatter_delimiter: ['---', '---']
  show_raw: true
  editor_components: [
    'image', 'code-block', 'quote', 'bulleted-list', 
    'numbered-list', 'table', 'enhanced-image', 
    'advanced-table', 'styled-text', 'font-style'
  ]
  toolbar_buttons: [
    'bold', 'italic', 'strikethrough', 'code', 'link', 
    'heading-one', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six',
    'quote', 'bulleted-list', 'numbered-list', 'insert-image', 'table', 
    'undo', 'redo', 'formatting', 'horizontal-rule', 'indent', 'outdent'
  ]

# slug配置
slug:
  encoding: "unicode"
  clean_accents: false
  sanitize_replacement: "-"

# 支持中文的配置
locale: 'zh_Hans'

# 清除本地缓存
local_backend_cache: false

collections:
  - name: "books"
    label: "书籍"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", required: true, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { label: "描述", name: "description", widget: "string", required: false, hint: "书籍简短描述" }
      - { label: "封面", name: "cover", widget: "image", required: false, hint: "书籍封面图片" }

  - name: "chapters"
    label: "章节"
    folder: "content/chapters"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", required: true, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { 
          label: "所属书籍", 
          name: "book", 
          widget: "relation",
          collection: "books",
          search_fields: ["title"],
          value_field: "{{slug}}",
          display_fields: ["title"],
          required: true
        }
      - { label: "章节 ID", name: "id", widget: "string", required: false, hint: "可选，用于唯一标识" }
      - { label: "缩略图", name: "thumb", widget: "image", required: false, hint: "可选，章节缩略图" }
      - { 
          label: "正文", 
          name: "body", 
          widget: "markdown",
          editor_components: ["image", "code-block", "quote"],
          media_library: {
            config: {
              multiple: true
            }
          },
          default: "在这里编写章节内容...",
          hint: "支持图文混排，可以粘贴保留格式的文本，使用Ctrl+Shift+V保留格式粘贴"
        }

  - name: "settings"
    label: "设置"
    files:
      - name: "chaptersData"
        label: "章节列表 (顺序)"
        file: "data/chapters.yaml"
        fields:
          - label: "章节"
            name: "chapters"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "标题", name: "title", widget: "string" }
              - { label: "缩略图", name: "thumb", widget: "string" }